import assert from 'node:assert/strict'
import { chromium } from 'playwright'
import { products } from '../lib/mock-data.ts'

const baseURL = process.env.TEST_BASE_URL ?? 'http://127.0.0.1:3001'
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined, args: ['--no-sandbox'] })
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } })
  // The popup rail must render and scroll on phones and desktop alike.
  for (const width of [390, 1440]) {
    await page.setViewportSize({ width, height: 844 })
    await page.context().addCookies([{ name: 'mm_cart', value: Buffer.from(JSON.stringify([{ productId: products[0].id, quantity: 1 }])).toString('base64url'), url: baseURL }])
    await page.goto(`${baseURL}/shop`)
    await page.getByRole('link', { name: /Shopping cart/ }).click()
    const popup = page.getByRole('dialog', { name: 'Your cart' })
    const suggestions = popup.getByRole('region', { name: 'Cart recommendations', exact: true })
    await suggestions.waitFor()
    const scroller = suggestions.getByRole('group', { name: 'Suggested products' })
    assert.ok(await scroller.evaluate(element => element.scrollWidth > element.clientWidth), `Popup suggestions overflow at ${width}px`)
    await scroller.evaluate(element => { element.scrollLeft = element.scrollWidth })
    await page.waitForFunction(() => document.querySelector('dialog [aria-label="Suggested products"]').scrollLeft > 0)
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No page overflow at ${width}px`)
    await popup.getByRole('button', { name: 'Close cart' }).click()
    console.log(`PASS: popup cart recommendations render and scroll at ${width}px`)
  }
  await page.context().clearCookies()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(`${baseURL}/shop`)
  assert.equal(await page.locator('article').getByText('BACKORDER', { exact: true }).count(), 0)
  console.log('PASS: backorder cards have no backorder badge')
  await page.context().addCookies([{ name: 'mm_cart', value: Buffer.from(JSON.stringify([{ productId: products[0].id, quantity: 1 }])).toString('base64url'), url: baseURL }])
  await page.goto(`${baseURL}/cart`)
  const rail = page.getByRole('region', { name: 'Cart recommendations', exact: true })
  await rail.waitFor()
  assert.equal(await rail.getByText(products[0].name, { exact: true }).count(), 0)
  const readCart = () => page.evaluate(async () => (await fetch('/api/cart')).json())
  const before = await readCart()
  let releaseFullAdd
  const fullAddGate = new Promise(resolve => { releaseFullAdd = resolve })
  await page.route('**/cart', async route => {
    if (route.request().method() === 'POST') await fullAddGate
    await route.continue()
  })
  await rail.getByRole('button', { name: /Add .* to cart/ }).first().click()
  assert.equal(await page.getByRole('link', { name: 'PROCEED TO CHECKOUT', exact: true }).count(), 0, 'Full cart checkout waits for quick additions')
  releaseFullAdd()
  await page.waitForFunction(() => document.querySelector('a[aria-label="Shopping cart, 2 items"]'))
  const after = await readCart()
  assert.equal(after.lines.length, 2)
  assert.ok(after.subtotal > before.subtotal)
  assert.equal(await page.getByRole('dialog').isVisible(), false, 'Full-cart quick add should stay in the full cart')
  await page.getByRole('link', { name: /Shopping cart/ }).click()
  const drawer = page.getByRole('dialog', { name: 'Your cart' })
  const drawerRail = drawer.getByRole('region', { name: 'Cart recommendations', exact: true })
  await drawerRail.waitFor()
  for (const line of after.lines) assert.equal(await drawerRail.getByText(line.name, { exact: true }).count(), 0)
  const scroller = drawerRail.getByRole('group', { name: 'Suggested products' })
  assert.ok(await scroller.evaluate(el => el.scrollWidth > el.clientWidth), 'Recommendations should scroll horizontally')
  let releaseAdd
  const addGate = new Promise(resolve => { releaseAdd = resolve })
  await page.route('**/cart', async route => {
    if (route.request().method() === 'POST') await addGate
    await route.continue()
  })
  await drawerRail.getByRole('button', { name: /Add .* to cart/ }).first().click()
  assert.equal(await drawer.getByRole('link', { name: 'Checkout', exact: true }).count(), 0, 'Checkout waits for a recommendation addition')
  releaseAdd()
  await page.waitForFunction(() => document.querySelector('a[aria-label="Shopping cart, 3 items"]'))
  await drawer.getByRole('region', { name: 'Cart confirmation' }).waitFor()
  await drawer.getByRole('button', { name: 'Dismiss cart confirmation' }).click()
  await drawer.getByRole('link', { name: 'Checkout', exact: true }).waitFor()
  assert.equal((await readCart()).lines.length, 3)
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
  console.log('PASS: recommendations add in full cart and drawer, exclude cart items, update subtotal, and scroll on mobile')
  await drawer.getByRole('button', { name: 'Close cart' }).click()
  await page.goto(`${baseURL}/checkout`)
  await page.getByRole('link', { name: /Shopping cart/ }).click()
  await drawer.waitFor()
  assert.equal(await drawer.getByRole('region', { name: 'Cart recommendations' }).count(), 0, 'Checkout edits must go through full cart')
  await drawer.getByRole('button', { name: 'Close cart' }).click()
  const suit = products.find(product => product.slug === 'wetsuit-3mm')
  await page.context().addCookies([{ name: 'mm_cart', value: Buffer.from(JSON.stringify([{ productId: suit.id, quantity: 1 }])).toString('base64url'), url: baseURL }])
  await page.goto(`${baseURL}/cart`)
  await rail.getByRole('link', { name: 'Choose options for Neoprene Hood 3mm', exact: true }).waitFor()
  assert.equal(await rail.getByRole('button', { name: 'Add Neoprene Hood 3mm to cart' }).count(), 0)
  const backorder = rail.locator('article').filter({ hasText: 'Open Cell Wetsuit 5mm' })
  await backorder.getByRole('button', { name: /Add .* to cart/ }).click()
  await page.waitForFunction(() => document.querySelector('a[aria-label="Shopping cart, 2 items"]'))
  assert.ok((await readCart()).lines.some(line => line.stockStatus === 'onbackorder' && line.purchasable))
  await page.goto(`${baseURL}/products/hood-3mm`)
  await page.getByRole('link', { name: /Shopping cart/ }).click()
  await drawer.getByRole('link', { name: 'Choose options for Neoprene Hood 3mm', exact: true }).click()
  await drawer.waitFor({ state: 'hidden' })
  assert.ok(page.url().endsWith('/products/hood-3mm'), 'Same-product recommendation should close the drawer')
  await page.route('**/api/cart/recommendations', route => route.abort('failed'))
  await page.goto(`${baseURL}/cart`)
  await page.reload()
  await page.getByRole('link', { name: 'PROCEED TO CHECKOUT', exact: true }).waitFor()
  assert.equal(await rail.count(), 0, 'Recommendation outages must not block checkout')
  console.log('PASS: backorders add normally, variable suggestions require options, and recommendation outages preserve checkout')
} finally {
  await browser.close()
}
