import assert from 'node:assert/strict'
import { chromium } from 'playwright'

const baseURL = process.env.TEST_BASE_URL ?? 'http://127.0.0.1:3001'
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined, args: ['--no-sandbox'] })
try {
  for (const width of [360, 390, 1440]) {
    const page = await browser.newPage({ viewport: { width, height: 844 } })
    await page.goto(`${baseURL}/shop`)
    const add = page.getByRole('button', { name: /Add .* to cart/ }).first()
    await add.click()
    const banner = page.getByRole('region', { name: 'Cart confirmation' })
    await banner.waitFor({ timeout: 10000 })
    const confirmationImage = banner.getByRole('img')
    assert.equal(await confirmationImage.count(), 1, 'Confirmation includes the added product image')
    assert.ok((await confirmationImage.getAttribute('alt')).length > 0)
    const box = await banner.boundingBox()
    assert.ok(box.x >= 8 && box.y >= 8 && box.x + box.width <= width - 8, 'Confirmation floats with space around it')
    assert.ok(box.width <= 420, 'Confirmation remains a compact box on desktop')
    const drawer = page.getByRole('dialog', { name: 'Your cart' })
    assert.equal(await drawer.isVisible(), false, 'Adding keeps the drawer closed')
    assert.equal(await page.evaluate(() => document.body.style.overflow), '')
    assert.equal(await banner.evaluate(element => element.contains(document.activeElement)), false, 'Banner does not take focus')
    assert.ok(page.url().endsWith('/shop'))
    await banner.getByRole('button', { name: 'Dismiss cart confirmation' }).click()
    await banner.waitFor({ state: 'hidden' })
    await add.click()
    await banner.waitFor()
    await banner.waitFor({ state: 'hidden', timeout: 7000 })
    await add.click()
    await banner.waitFor()
    await banner.getByRole('button', { name: 'View cart', exact: true }).click()
    await drawer.waitFor()
    const bounds = await drawer.boundingBox()
    assert.ok(bounds.x >= width * 0.09, 'Shopping remains visible on the left')
    await page.mouse.click(bounds.x / 2, 400)
    await drawer.waitFor({ state: 'hidden' })
    await page.goto(`${baseURL}/cart`)
    const back = page.getByRole('link', { name: 'Continue shopping', exact: true })
    assert.equal(await back.getAttribute('href'), '/shop')
    const backBounds = await back.boundingBox()
    assert.ok(backBounds.x + backBounds.width / 2 > width / 2, 'Continue shopping is on the right')
    const rail = page.getByRole('region', { name: 'Cart recommendations', exact: true })
    await rail.getByRole('button', { name: /Add .* to cart/ }).first().click()
    await banner.waitFor()
    assert.equal(await drawer.isVisible(), false)
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
    await banner.getByRole('button', { name: 'View cart', exact: true }).click()
    await drawer.getByRole('region', { name: 'Cart recommendations', exact: true }).getByRole('button', { name: /Add .* to cart/ }).first().click()
    await drawer.getByRole('region', { name: 'Cart confirmation' }).waitFor()
    await page.keyboard.press('Escape')
    await drawer.waitFor({ state: 'hidden' })
    await page.getByRole('link', { name: /Shopping cart/ }).click()
    await drawer.waitFor()
    assert.equal(await drawer.getByRole('region', { name: 'Cart confirmation' }).count(), 0, 'Closing clears the drawer confirmation')
    await drawer.getByRole('button', { name: 'Close cart' }).click()
    await back.click()
    await page.waitForURL('**/shop')
    await page.context().clearCookies()
    await page.goto(`${baseURL}/cart`)
    await page.getByRole('link', { name: 'Continue shopping', exact: true }).waitFor()
    console.log(`PASS: addition banner, dismissal, timeout, drawer gap, and continue shopping at ${width}px`)
    await page.close()
  }
} finally { await browser.close() }
