import assert from 'node:assert/strict'
import { chromium } from 'playwright'
const baseURL=process.env.TEST_BASE_URL??'http://localhost:3001'
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']})
try{
 for(const width of [320,390,1440]){
  const page=await browser.newPage({viewport:{width,height:900}})
  await page.goto(`${baseURL}/fins`)
  const first=page.getByRole('article').nth(0), second=page.getByRole('article').nth(1)
  await first.getByRole('button',{name:/Add .* to comparison/}).click({timeout:8000})
  await second.getByRole('button',{name:/Add .* to comparison/}).click()
  const tray=page.getByRole('region',{name:'Product comparison tray'})
  await tray.waitFor()
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('mm_compare_v1')).length),2)
  assert.ok(page.url().endsWith('/fins'),'Selecting does not navigate')
  await page.reload();await tray.getByRole('link',{name:'Compare selected products'}).waitFor()
  await page.getByRole('link',{name:/Shopping cart/}).click()
  const drawer=page.getByRole('dialog',{name:'Your cart'});await drawer.waitFor()
  assert.equal(await tray.isVisible(),false,'Tray hides during modal cart')
  await drawer.getByRole('button',{name:'Close cart'}).click()
  await tray.getByRole('link',{name:'Compare selected products'}).click()
  await page.waitForURL('**/compare')
  await page.getByRole('table',{name:'Product comparison'}).waitFor()
  const headers=await page.getByRole('columnheader').count();assert.equal(headers,3)
  await page.getByRole('checkbox',{name:'Highlight differences'}).check()
  assert.ok(await page.locator('[data-different="true"]').count()>0)
  const scroll=page.getByRole('region',{name:'Scrollable product comparison'})
  if(width<600){
   const canScroll=await scroll.evaluate(element=>element.scrollWidth>element.clientWidth);assert.equal(canScroll,true)
   await scroll.evaluate(element=>{element.scrollLeft=200})
   assert.ok(await scroll.evaluate(element=>element.scrollLeft>0))
  }
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No document overflow')
  const title=await page.getByRole('heading',{name:'Compare products',exact:true}).boundingBox()
  const header=await page.getByRole('banner').boundingBox();assert.ok(title.y>=header.y+header.height)
  await page.getByRole('table').getByRole('button',{name:/Remove .* from comparison/}).first().click()
  await page.getByText('Add one more product to compare.').waitFor()
  await page.getByRole('button',{name:'Clear comparison',exact:true}).click()
  await page.getByText('No products selected for comparison').waitFor()
  console.log(`PASS compare selection, persistence, dialog, aligned table, highlights, removal and layout at ${width}px`)
  await page.close()
 }
 const page=await browser.newPage({viewport:{width:390,height:900}})
 await page.goto(`${baseURL}/fins`)
 await page.getByRole('article').first().getByRole('button',{name:/Add .* to comparison/}).click()
 await page.goto(`${baseURL}/suits`)
 await page.getByRole('article').first().getByRole('button',{name:/Add .* to comparison/}).click()
 await page.getByRole('region',{name:'Product comparison tray'}).getByText(/Compare products from the same category/).waitFor()
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('mm_compare_v1')).length),1)
 await page.goto(`${baseURL}/fins`)
 await page.getByRole('article').nth(1).getByRole('button',{name:/Add .* to comparison/}).click()
 await page.getByRole('article').first().getByRole('link').first().click()
 await page.waitForURL('**/products/**')
 await page.getByRole('button',{name:/Remove .* from comparison/}).first().waitFor()
 const tray=page.getByRole('region',{name:'Product comparison tray'});const bounds=await tray.boundingBox()
 assert.ok(bounds.y+bounds.height<=900-80,'Tray leaves room for PDP mobile purchasing')
 console.log('PASS category guard and PDP comparison state/mobile purchase clearance')
 await page.goto(`${baseURL}/compare`)
 const selectedIds=await page.evaluate(()=>JSON.parse(localStorage.getItem('mm_compare_v1')).map(item=>item.id))
 let mode='attributes'
 await page.route('**/api/compare?*',async route=>{
  if(mode==='outage'){await route.fulfill({status:503,json:{error:'Unavailable'}});return}
  const response=await route.fetch();const data=await response.json();data.products.sort((a,b)=>selectedIds.indexOf(a.id)-selectedIds.indexOf(b.id))
  if(mode==='deleted')data.products=data.products.slice(0,1)
  if(mode==='attributes'){
   data.products[0].attributes.push({key:'wc:777',name:'Blade material',values:['Carbon']})
   data.products[1].attributes.push({key:'wc:777',name:'Material',values:['Fiberglass']},{key:'wc:778',name:'New specification',values:['New value']})
  }
  await route.fulfill({json:data})
 })
 await page.reload()
 const material=page.getByRole('row',{name:/Blade material Carbon Fiberglass/});await material.waitFor()
 await page.getByRole('row',{name:/New specification Not specified New value/}).waitFor()
 console.log('PASS dynamic attributes, shared-ID alignment and missing values')
 mode='outage';await page.reload();await page.getByRole('button',{name:'Retry comparison'}).waitFor()
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('mm_compare_v1')).length),2)
 mode='deleted';await page.getByRole('button',{name:'Retry comparison'}).click()
 await page.getByText(/is no longer available/).waitFor()
 await page.getByRole('button',{name:/Remove unavailable .* from comparison/}).click()
 await page.getByText('Add one more product to compare.').waitFor()
 console.log('PASS outage preserves selection, retry and unavailable product removal')
 await page.close()
 const recovery=await browser.newPage({viewport:{width:390,height:900}})
 await recovery.goto(`${baseURL}/fins`)
 await recovery.getByRole('article').first().getByRole('button',{name:/Add .* to comparison/}).click()
 await recovery.evaluate(()=>{
  window.compareOriginalSetItem=Storage.prototype.setItem
  Storage.prototype.setItem=function(key,value){if(key==='mm_compare_v1')throw Error('Storage blocked');return window.compareOriginalSetItem.call(this,key,value)}
 })
 await recovery.getByRole('button',{name:'Clear comparison',exact:true}).click()
 await recovery.getByRole('button',{name:'Retry comparison save'}).waitFor()
 await recovery.getByRole('button',{name:'Open menu'}).click()
 await recovery.getByRole('link',{name:'COMPARE PRODUCTS',exact:true}).click()
 await recovery.getByRole('button',{name:'Retry comparison save'}).waitFor()
 await recovery.evaluate(()=>{Storage.prototype.setItem=window.compareOriginalSetItem})
 await recovery.getByRole('button',{name:'Retry comparison save'}).click()
 await recovery.getByRole('button',{name:'Retry comparison save'}).waitFor({state:'hidden'})
 assert.deepEqual(await recovery.evaluate(()=>JSON.parse(localStorage.getItem('mm_compare_v1'))),[])
 console.log('PASS failed final clear stays visible and retries from tray and comparison page')
}catch(error){throw error}finally{await browser.close()}
