import assert from 'node:assert/strict'
import { chromium } from 'playwright'

const baseURL = process.env.TEST_BASE_URL ?? 'http://localhost:3001'
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/usr/bin/chromium', args: ['--no-sandbox'] })
try {
  const page = await browser.newPage({ viewport: { width: 320, height: 844 } })
  await page.goto(`${baseURL}/shop`)
  const card = page.getByRole('article').first()
  const save = card.getByRole('button', { name: /Add .* to wishlist/ })
  await save.waitFor({ timeout: 8000 })
  await save.click()
  await card.getByRole('button', { name: /Remove .* from wishlist/ }).waitFor()
  assert.ok(page.url().endsWith('/shop'), 'Heart must not navigate')
  await page.getByRole('link', { name: 'Wishlist, 1 saved products' }).click()
  await page.waitForURL('**/wishlist')
  await page.getByRole('article').waitFor()
  const title=await page.getByRole('heading',{name:'Your wishlist',exact:true}).boundingBox()
  const header=await page.getByRole('banner').boundingBox()
  assert.ok(title.y>=header.y+header.height,'Wishlist title must remain visible below sticky navigation')
  await page.reload()
  await page.getByRole('article').waitFor()
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Wishlist fits mobile')
  await page.getByRole('article').first().getByRole('link').first().click()
  await page.waitForURL('**/products/**')
  const pdpHeart = page.getByRole('button', { name: /Remove .* from wishlist/ }).first()
  await pdpHeart.waitFor()
  await pdpHeart.click()
  await page.getByRole('link', { name: 'Wishlist', exact: true }).click()
  await page.getByText('Your wishlist is empty').waitFor()
  console.log('PASS guest card/PDP wishlist, persistence, count, removal and 320px layout')
  await page.goto(`${baseURL}/shop`)
  const simple=page.getByRole('article').filter({has:page.getByRole('button',{name:/Add .* to cart/})}).first()
  await simple.getByRole('button',{name:/Add .* to wishlist/}).click()
  await page.getByRole('link',{name:'Wishlist, 1 saved products'}).click()
  await page.waitForURL('**/wishlist')
  const savedProduct=page.getByRole('article').first()
  await savedProduct.getByRole('button',{name:/Add .* to cart/}).click()
  await page.getByRole('region',{name:'Cart confirmation'}).waitFor()
  assert.equal(await savedProduct.getByRole('button',{name:/Remove .* from wishlist/}).count(),1,'Adding to cart keeps the wishlist save')
  console.log('PASS wishlist quick-add uses floating cart confirmation and keeps the save')
} finally { await browser.close() }
